### PR TITLE
Publish compiled mixin like mimir

### PR DESCRIPTION
**Pull request by pracucci**
**What this PR does**:
I'm leading an effort to improve and uniform Mimir, Loki and Tempo monitoring. This includes publishing the compiled mixin and runbooks. I see Tempo already does both (good job!). As a further step, I would like to align the location of the published mixin to the Mimir one.

Do you have any concern if we move it to `operations/tempo-mixin-compiled` and move dashboards to a dedicated folder?

**Which issue(s) this PR fixes**:
N/A

**Checklist**
- [ ] Tests updated
- [ ] Documentation added
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Comment by joe-elliott** [comment]
No issues here with moving the location. I feel like it's easier to find in the new folder. 

Currently we also compile `./operations/jsonnet` to `./operations/kube-manifests`. Thoughts on changing that folder name to align with this change? `./operations/jsonnet` => `./operations/jsonnet-compiled`? WDYT?

**Comment by pracucci** [comment]
> Currently we also compile ./operations/jsonnet to ./operations/kube-manifests. Thoughts on changing that folder name to align with this change? ./operations/jsonnet => ./operations/jsonnet-compiled? WDYT?

I think it makes sense. If you don't mind, I will do it in a separate PR, to keep changes separated.

**Comment by pracucci** [comment]
> > Currently we also compile ./operations/jsonnet to ./operations/kube-manifests. Thoughts on changing that folder name to align with this change? ./operations/jsonnet => ./operations/jsonnet-compiled? WDYT?
> 
> I think it makes sense. If you don't mind, I will do it in a separate PR, to keep changes separated.

See: https://github.com/grafana/tempo/pull/1454

**Review by annanay25 — APPROVED** [review]
This LGTM. Thanks.

One comment: Since the mixin is auto-vendored into our internal environment, we will have to update the new location so our vendor bots can continue to find the mixin.

**Comment by pracucci** [comment]
> One comment: Since the mixin is auto-vendored into our internal environment, we will have to update the new location so our vendor bots can continue to find the mixin.

I don't understand this. Our internal environment vendor the jsonnet, not the compiled one. This PR only moves the location of the compiled `.yaml` and `.json`, so how does it affect our internal environment?

**Pull request merged**
