### PR TITLE
fix relref, add local docs preview/test, add website sync test

### PR DESCRIPTION
**Pull request by robbymilo**
**What this PR does**:

https://github.com/grafana/tempo/pull/705 introduced a relref error in the website build.

This PR fixes the relref error, and also adds a test to the github action to prevent the website sync from occurring if there are any errors. It also adds a Makefile to preview the docs locally.

### CODE REVIEW

**Comment by joe-elliott** [comment]
thx robby!

@annanay25 @mdisibio 

is this the step we removed b/c it kept timing out?

**Comment by annanay25** [comment]
Yes that's right. It was done in #634

**Comment by joe-elliott** [comment]
Cool, let's give it another shot. It worked on this PR and it would be nice to check for errors like this.

**Review by joe-elliott — APPROVED** [review]
Awesome, Thanks!

**Pull request merged**
