### PR TITLE
Restore default overrides in tempo-overrides ConfigMap

### LINKED ISSUE #1148: tempo-overrides ConfigMap does not contain the expected overrides
**Describe the bug**

`tempo-overrides` ConfigMap does not contain the expected `overrides` according to: https://github.com/grafana/tempo/blob/main/operations/jsonnet/microservices/config.libsonnet

**To Reproduce**
1. Deploy Tempo with Tanka using the microprofile version 
2. Open `tempo-overrides` ConfigMap, it does not contain the overrides reported here https://github.com/grafana/tempo/blob/865546d60027fbf89acd57f004fec4672146d0dc/operations/jsonnet/microservices/config.libsonnet#L108

**Expected behavior**

`tempo-overrides` shoud have the overrides reported here https://github.com/grafana/tempo/blob/865546d60027fbf89acd57f004fec4672146d0dc/operations/jsonnet/microservices/config.libsonnet#L108

**Environment:**
 - Infrastructure: [e.g., Kubernetes, bare-metal, laptop] Kubernetes 
 - Deployment tool: [e.g., helm, jsonnet] Tanka

**Additional Context**

### PR DESCRIPTION
**Pull request by irizzant**
**What this PR does**:
This PR restore the default overrides for tempo-overrides ConfigMap

**Which issue(s) this PR fixes**:
Fixes #1148 

**Checklist**
- [X] Tests updated
- [X] Documentation added
- [X] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Comment by joe-elliott** [comment]
CI failed but it's only b/c you corrected the issue. If you run 
```
make kube-manifests-check
```
It will regenerate the k8s manifests locally. Commit and push that and CI should pass.

Nice find and thx for the fix!

**Comment by irizzant** [comment]
Hi 
I've updated the manifests as requested.
Thank you

**Comment by joe-elliott** [comment]
@irizzant it seems we were having issues with a floating version of jsonnet and tanka in our CI. If you merge main it might fix your issue.

**Comment by irizzant** [comment]
@joe-elliott 
ok now it makes sense! Now all the checks are green

**Review by joe-elliott — APPROVED** [review]

**Comment by joe-elliott** [comment]
nice!

Thanks for the fix :)

**Pull request merged**
