### PR TITLE
[DOC] Remove traceQLStreaming feature flag

### PR DESCRIPTION
**Pull request by knylander-grafana**
**What this PR does**:

Removes the traceQLStreaming feature toggle, per https://github.com/grafana/grafana/issues/94528

Also, updates the version of Grafana to 11.2 in some of the docker-compose files that reference the feature toggle. 

**Which issue(s) this PR fixes**:
Part of https://github.com/grafana/grafana/issues/94528

**Checklist**
- [ ] Tests updated
- [X] Documentation added
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Review by kvrhdn — COMMENTED** [review]
This looks okay to me but for the examples to work with streaming we need to change something in the data source configuration here:

https://github.com/grafana/tempo/blob/main/example/docker-compose/shared/grafana-datasources.yaml#L27-L30

If you run the docker-compose example, the Tempo data source has streaming disabled.

I'm trying to track down what the config name is in Grafana...

**Comment by knylander-grafana** [comment]
> This looks okay to me but for the examples to work with streaming we need to change something in the data source configuration here:
> 
> [`main`/example/docker-compose/shared/grafana-datasources.yaml#L27-L30](https://github.com/grafana/tempo/blob/main/example/docker-compose/shared/grafana-datasources.yaml?rgh-link-date=2024-10-15T16%3A57%3A32Z#L27-L30)
> 
> If you run the docker-compose example, the Tempo data source has streaming disabled.
> 
> I'm trying to track down what the config name is in Grafana...

Oh! I wonder if the requirement for Grafana for these to work is 11.3. I think the feature toggle is being removed then. I'll message you a Slack thread that has some additional information.

**Comment by kvrhdn** [comment]
That should be this change:

```diff
diff --git a/example/docker-compose/shared/grafana-datasources.yaml b/example/docker-compose/shared/grafana-datasources.yaml
index 4a3bc2c4e..794d5a1d5 100644
--- a/example/docker-compose/shared/grafana-datasources.yaml
+++ b/example/docker-compose/shared/grafana-datasources.yaml
@@ -28,3 +28,5 @@ datasources:
     httpMethod: GET
     serviceMap:
       datasourceUid: prometheus
+    streamingEnabled:
+      search: true
```

Want me to push this change to the PR or can you add it?

**Comment by kvrhdn** [comment]
Yep I can confirm with this setting you get `Streaming: Enabled` in explore :+1:

Screenshot 2024-10-15 at 19 08 54

**Comment by knylander-grafana** [comment]
Awesome! Thank you. You're faster than me :) I just added the change. I can push the update.

**Review by kvrhdn — APPROVED** [review]

**Comment by kvrhdn** [comment]
> Do we need to add this to the docs?

I think it might be nice to have an example of the yaml config either in our docs or in Grafana.

It would also fit well on this page: https://grafana.com/docs/grafana/next/datasources/tempo/configure-tempo-data-source/#streaming
There is an example yaml file at the bottom but it doesn't have the `streamingEnabled` setting.

**Comment by knylander-grafana** [comment]
I will add that example to the Grafana docs. Thank you for finding a spot. https://github.com/grafana/grafana/pull/94751

**Pull request merged**
