### PR TITLE
fix make vendor-check

### LINKED ISSUE #3905: compile issue when make vendor-check
**Describe the bug**

I read the Contributing.md, run `make vendor-check`.
When the code  run  `gen-traceql-local` , some error happen as follow

```
--
-- Gen proto --
--
docker run --rm -u 501 -v/Users/xiaokun/code/github.com/grafana/tempo:/Users/xiaokun/code/github.com/grafana/tempo -w/Users/xiaokun/code/github.com/grafana/tempo otel/build-protobuf:0.23.0 --proto_path=/Users/xiaokun/code/github.com/grafana/tempo -Ipkg/.patched-proto --gogofaster_out=plugins=grpc,paths=source_relative:./pkg/tempopb/ pkg/.patched-proto/common/v1/common.proto
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
docker run --rm -u 501 -v/Users/xiaokun/code/github.com/grafana/tempo:/Users/xiaokun/code/github.com/grafana/tempo -w/Users/xiaokun/code/github.com/grafana/tempo otel/build-protobuf:0.23.0 --proto_path=/Users/xiaokun/code/github.com/grafana/tempo -Ipkg/.patched-proto --gogofaster_out=plugins=grpc,paths=source_relative:./pkg/tempopb/ pkg/.patched-proto/resource/v1/resource.proto
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
docker run --rm -u 501 -v/Users/xiaokun/code/github.com/grafana/tempo:/Users/xiaokun/code/github.com/grafana/tempo -w/Users/xiaokun/code/github.com/grafana/tempo otel/build-protobuf:0.23.0 --proto_path=/Users/xiaokun/code/github.com/grafana/tempo -Ipkg/.patched-proto --gogofaster_out=plugins=grpc,paths=source_relative:./pkg/tempopb/ pkg/.patched-proto/trace/v1/trace.proto
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
docker run --rm -u 501 -v/Users/xiaokun/code/github.com/grafana/tempo:/Users/xiaokun/code/github.com/grafana/tempo -w/Users/xiaokun/code/github.com/grafana/tempo otel/build-protobuf:0.23.0 --proto_path=/Users/xiaokun/code/github.com/grafana/tempo -Ipkg/.patched-proto --gogofaster_out=plugins=grpc,paths=source_relative:./ pkg/tempopb/tempo.proto
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
docker run --rm -u 501 -v/Users/xiaokun/code/github.com/grafana/tempo:/Users/xiaokun/code/github.com/grafana/tempo -w/Users/xiaokun/code/github.com/grafana/tempo otel/build-protobuf:0.23.0 --proto_path=/Users/xiaokun/code/github.com/grafana/tempo -Ipkg/.patched-proto -Ivendor -Ivendor/github.com/gogo/protobuf --gogofaster_out=plugins=grpc,paths=source_relative:./ modules/frontend/v1/frontendv1pb/frontend.proto
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
rm -rf pkg/.patched-proto
go mod vendor
go mod tidy -e
/Library/Developer/CommandLineTools/usr/bin/make -C cmd/tempo-serverless update-mod
cd lambda && go mod tidy -e
cd cloud-run && go mod tidy -e
docker run --rm -v/Users/xiaokun/code/github.com/grafana/tempo:/src/loki grafana/loki-build-image:0.21.0 gen-traceql-local
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
make: Entering directory '/src/loki'
go: errors parsing go.mod:
/src/loki/go.mod:3: invalid go version '1.22.4': must match format 1.23
goyacc -o pkg/traceql/expr.y.go pkg/traceql/expr.y && rm y.output

conflicts: 1 shift/reduce
make: Leaving directory '/src/loki'
go run ./pkg/parquetquerygen/predicates.go > ./pkg/parquetquery/predicates.gen.go
git diff --exit-code -- **/go.sum **/go.mod vendor/ pkg/tempopb/ pkg/traceql/
```

The error info looks like https://github.com/golang/go/issues/61888, but i do't know if this is relate to `grafana/loki-build-image:0.21.0`

i also find the ci step is failed , but the ci step is passed .  
see ci log https://github.com/grafana/tempo/actions/runs/10085732303/job/27887063416#step:5:804

**To Reproduce**
1. Start Tempo (SHA or version)
2. Perform Operations (Read/Write/Others)

**Expected behavior**
compile success

**Environment:**
 - Infrastructure:  macbook m3
 - Deployment tool: 
 - Golang version: go version go1.22.4 darwin/arm64

**Additional Context**

### PR DESCRIPTION
**Pull request by shalk**
**What this PR does**:

**Which issue(s) this PR fixes**:
Fixes #3905 

**Checklist**
- [ ] Tests updated
- [ ] Documentation added
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Review by joe-elliott — CHANGES_REQUESTED** [review]
i saw the issue, but i'd prefer to keep using a container to run yacc instead of requiring everyone to install yacc locally.

**Comment by shalk** [comment]
> i saw the issue, but i'd prefer to keep using a container to run yacc instead of requiring everyone to install yacc locally.

I keep the container, and i found the golang version in grafana/loki-build-image:0.21.0 is too low.
loki-build-image 0.33.2 's golang version is 1.22.5
It works.

But I think it is hard to keep the version consistent with loki-build-image. should we use golang:1.22 instead ?

**Comment by javiermolinar** [comment]
> > i saw the issue, but i'd prefer to keep using a container to run yacc instead of requiring everyone to install yacc locally.
> 
> I keep the container, and i found the golang version in grafana/loki-build-image:0.21.0 is too low. loki-build-image 0.33.2 's golang version is 1.22.5 It works.
> 
> But I think it is hard to keep the version consistent with loki-build-image. should we use golang:1.22 instead ?

Maybe Tempo should have it's own build image

**Comment by joe-elliott** [comment]
> loki-build-image 0.33.2 's golang version is 1.22.5
> It works.

Let's just update to 0.33.2 if that works.

>  should we use golang:1.22 instead ?

I honestly don't know how floating the patch works in a go.mod.

> Maybe Tempo should have it's own build image

When/if we need to we can make our own. Otherwise we may as well share work with Loki.

**Review by joe-elliott — APPROVED** [review]

**Pull request merged**
