### PR TITLE
feat: Add tracing integration to profiling.

### PR DESCRIPTION
**Pull request by cyriltovena**
**What this PR does**:

This adds tracing integration to pprof profiling. Every root span ID per service will be added to the profiling data using pprof labels and then forward to Pyroscope.

This allows to show flamegraph for a given trace

image

Which can be useful to understand resource usage per trace.

**Which issue(s) this PR fixes**:
Fixes #<issue number>

**Checklist**
- [x] Tests updated
- [x] Documentation added
- [x] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Comment by cyriltovena** [comment]
Not sure why windows build is failing.

```
 error=failed to build for windows_amd64_v1: exit status 1
....
vendor/github.com/mattn/go-ieproxy/ieproxy_windows.go:22:6: getConf redeclared in this block
	vendor/github.com/mattn/go-ieproxy/ieproxy_unix.go:6:6: other declaration of getConf
vendor/github.com/mattn/go-ieproxy/ieproxy_windows.go:28:6: reloadConf redeclared in this block
	vendor/github.com/mattn/go-ieproxy/ieproxy_unix.go:10:6: other declaration of reloadConf
vendor/github.com/mattn/go-ieproxy/ieproxy_windows.go:133:6: overrideEnvWithStaticProxy redeclared in this block
	vendor/github.com/mattn/go-ieproxy/ieproxy_unix.go:14:6: other declaration of overrideEnvWithStaticProxy
vendor/github.com/mattn/go-ieproxy/pac_windows.go:9:29: method ProxyScriptConf.findProxyForURL already declared at vendor/github.com/mattn/go-ieproxy/pac_unix.go:6:29
```

**Comment by knylander-grafana** [comment]
@cyriltovena I saw that you checked the Documentation added box. Did you update doc or just add the changelog entry? If the latter, we can make a doc issue to update the Tempo doc and other doc sets, as needed.

**Review by joe-elliott — COMMENTED** [review]
Generally looks good but I think you need to run:

```
make update-mod
```

to tidy up the serverless go.mods

**Comment by cyriltovena** [comment]
> @cyriltovena I saw that you checked the Documentation added box. Did you update doc or just add the changelog entry? If the latter, we can make a doc issue to update the Tempo doc and other doc sets, as needed.

I don't think this needs to be mentioned in the doc. This is why I checked that box. I think a changelog entry is enough yes.

**Comment by mdisibio** [comment]
> Not sure why windows build is failing.
> 
> ```
>  error=failed to build for windows_amd64_v1: exit status 1
> ....
> vendor/github.com/mattn/go-ieproxy/ieproxy_windows.go:22:6: getConf redeclared in this block
> 	vendor/github.com/mattn/go-ieproxy/ieproxy_unix.go:6:6: other declaration of getConf
> vendor/github.com/mattn/go-ieproxy/ieproxy_windows.go:28:6: reloadConf redeclared in this block
> 	vendor/github.com/mattn/go-ieproxy/ieproxy_unix.go:10:6: other declaration of reloadConf
> vendor/github.com/mattn/go-ieproxy/ieproxy_windows.go:133:6: overrideEnvWithStaticProxy redeclared in this block
> 	vendor/github.com/mattn/go-ieproxy/ieproxy_unix.go:14:6: other declaration of overrideEnvWithStaticProxy
> vendor/github.com/mattn/go-ieproxy/pac_windows.go:9:29: method ProxyScriptConf.findProxyForURL already declared at vendor/github.com/mattn/go-ieproxy/pac_unix.go:6:29
> ```

We are getting this on other PRs too.  This fix works locally, I will test it on my PR:
```
github.com/mattn/go-ieproxy v0.0.11 // indirect
```

**Comment by cyriltovena** [comment]
hey that's seems stale ?

**Comment by joe-elliott** [comment]
@cyriltovena i'm good on this PR. if you can work out the conflicts we'll merge

**Review by joe-elliott — APPROVED** [review]

**Pull request merged**
