### PR TITLE
Operator api docs

### PR DESCRIPTION
**Pull request by pavolloffay**
**What this PR does**:

**Which issue(s) this PR fixes**:
Fixes #<issue number>

**Checklist**
- [ ] Tests updated
- [x] Documentation added
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Comment by pavolloffay** [comment]
@knylander-grafana could you please review?

**Review by knylander-grafana — APPROVED** [review]
Thank you for adding the information.

**Comment by knylander-grafana** [comment]
@pavolloffay you should be able to merge this when you are ready. If not, let me know and I"ll merge it for you.

**Comment by pavolloffay** [comment]
@knylander-grafana I don't have merge rights, please merge it for me

**Pull request merged**
