### PR TITLE
Backport https://github.com/cortexproject/cortex/pull/4897 to fix IDMSv1

### LINKED ISSUE #2743: Storage S3 - AWS node role IMDSv1 does not work after upgrade to v2.2
**Describe the bug**
Tempo does not start with "transparent" AWS credentials (node role). It seems to not take the credentials/role into account at all.

**To Reproduce**
1. Start from tempo-distributed chart
2. Use node role credentials to connect to S3
3. Fail with `"err":"failed to init module services error initialising module: store: failed to create store unexpected error from ListObjects on <bucket name>: Access Denied"`

**Expected behavior**
Tempo connects and starts.

**Environment:**
 - Kubernetes
 - Helm chart tempo-distributed >=1.5.3

**Additional Context**
- Just downgrading image version while using the very same config fixes the problem, so must be code or image related issue.
- I also though about missing some niche permission in the attached policy so I temporarily granted `*` to the node role but no joy.

### PR DESCRIPTION
**Pull request by coufalja**
**What this PR does**:
Backports Cortex fix to tempo to fix issue with IDMSv1 and node role auth.

**Which issue(s) this PR fixes**:
Fixes #2743 

**Checklist**
- [ ] Tests updated
- [ ] Documentation added
- [x] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Review by zalegrala — COMMENTED** [review]
This looks good to me.  Thanks for the PR.  I tested an image with this change against minio and things work as expected.  I've not had a chance to test against s3 when node role is not in use, which I think would be good to do before merge.

**Review by zalegrala — APPROVED** [review]
I was able to test this change against s3 also.  Thanks for the PR.

**Comment by coufalja** [comment]
@zalegrala Hi, any chance this could get backported to 2.2? It blocks us adopting the 2.2.x series.

**Comment by joe-elliott** [comment]
@coufalja thank you for this PR. @zalegrala championed this internally and we decided to cut quick 2.2.2. We appreciate your help improving Tempo :pray:

**Comment by coufalja** [comment]
Thats awesome, thank you!

**Comment by joe-elliott** [comment]
2.2.2 released
- https://github.com/grafana/tempo/releases/tag/v2.2.2
- https://hub.docker.com/r/grafana/tempo/tags?page=1&name=2.2

**Pull request merged**
