### PR TITLE
readme: fix link to query editor example

### PR DESCRIPTION
**Pull request by frzifus**
**What this PR does**:
markdown-link-check randomly discovered 404 when requesting the example image source. This PR resolves this.

### CODE REVIEW

**Comment by joe-elliott** [comment]
thanks for the fix! going to ping @knylander-grafana b/c she knows our standards for building links to other docs

**Comment by knylander-grafana** [comment]
> **What this PR does**: markdown-link-check randomly discovered 404 when requesting the example image source. This PR resolves this.

Greetings. 

Thank you for opening a PR and contributing. 

Grafana docs store our media assets in cloud storage. When we use an image link for an asset stored in the cloud storage, the correct format is `/media/docs/...` instead of a fully qualified URL. The image link your link checker marked as wrong is actually correct. 

For more information, refer to [Add an image to a markdown file](https://grafana.com/docs/writers-toolkit/write/image-guidelines/#add-an-image-to-a-markdown-file) in the Writers' Toolkit.

**Comment by knylander-grafana** [comment]
You're absolutely right! The image doesn't appear in the README. Let me test it with the full URL. 

Normally, Grafana docs store our media assets in cloud storage. When we use an image link for an asset stored in the cloud storage, the correct format is `/media/docs/...` instead of a fully qualified URL. 

For more information, refer to [Add an image to a markdown file](https://grafana.com/docs/writers-toolkit/write/image-guidelines/#add-an-image-to-a-markdown-file) in the Writers' Toolkit.
 
If you ever have a question about whether an image link works, you can build the docs locally and see if the image appears. Instructions are also in the Writers' Toolkit: [grafana.com/docs/writers-toolkit/review/test-documentation-changes](https://grafana.com/docs/writers-toolkit/review/test-documentation-changes/)

**Review by knylander-grafana — APPROVED** [review]
Thank you for catching this! I made this error because for our docs we don't use the fully qualified URL.

**Comment by knylander-grafana** [comment]
@joe-elliott You might need to approve since my approval didn't clear for merging.

**Pull request merged**
