### PR TITLE
Remove ReuseTraceBytes

### PR DESCRIPTION
**Pull request by joe-elliott**
**What this PR does**:
Removes usage of the bytepool.  We are using this incorrectly and, as written, will only cause panics.

This is complicated but at least two things are occurring which has me remove this for now:
- The prometheus slice pool is not guaranteed to return a slice of the size requested. The way we have written this code it is easy to panic with too small slice.
- gogoproto is not compatible with GRPC latest. I don't believe the custom classes are being used like we think they are.

All around this just requires more research. Removing it for now.

### CODE REVIEW

**Comment by mdisibio** [comment]
> * The prometheus slice pool is not guaranteed to return a slice of the size requested. The way we have written this code it is easy to panic with too small slice.
https://github.com/prometheus/prometheus/blob/main/pkg/pool/pool.go#L66  It looks like the slice returned is the size of the matching bucket.  The result could be resized to the needed length.

**Comment by annanay25** [comment]
Yeah, a subtle difference is that it will create a slice of _atleast_ minSize

**Comment by joe-elliott** [comment]
Yup, if it were that simple I'd go for that change, but I don't think we even really understand when this code is currently being run. I think we need to step back and really understand what it's doing before bringing it back in.

**Review by annanay25 — APPROVED** [review]

**Comment by joe-elliott** [comment]
Closing in favor of #698 for now.

**Pull request closed without merging**
