### PR TITLE
Extend /flush to support flushing a single tenant

### PR DESCRIPTION
**Pull request by kvrhdn**
**What this PR does**:
`/flush` will flush data for all the tenants, this PR extends the endpoint to also support `/flush?instance=...`. Flushing the data of single tenant can be useful in case you need to work on data of that single tenant.

**Which issue(s) this PR fixes**:
~~Fixes #<issue number>~~

**Checklist**
- [ ] ~~Tests updated~~
- [x] Documentation added
- [x] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Review by knylander-grafana — COMMENTED** [review]
Thank you for adding doc. Update looks good for docs.

**Review by mapno — APPROVED** [review]

**Review by zalegrala — APPROVED** [review]

**Comment by kvrhdn** [comment]
Oops, forgot about this one 🙃

**Comment by knylander-grafana** [comment]
@kvrhdn Do we want to backport the docs for this change to the Tempo 2.1 release? Your doc updates don't appear to be in the 2.1 docs.

**Comment by kvrhdn** [comment]
If it's not too much work, backporting this would be good. Not super critical imo, this addition to the endpoint has a very narrow use-case, so I doubt a lot of people if any will use this outside of us.

**Pull request merged**
