### PR TITLE
FIX-699: Add capability to completely flush on shutdown

### LINKED ISSUE #699: [Ingester] Add ability to completely flush on shutdown
**Is your feature request related to a problem? Please describe.**
When an ingester shuts down it is expected it will come back up, replay its wal and continue using the same disk. However, in some ephemeral deployments this is not true and it is desired for an ingester to always flush its entire contents to the backend on shutdown.

Add the ability for an ingester to always flush its entire disk to the backend.

Note: With this setting there may be gaps in trace availability. After the ingester shuts down but before the queriers get a chance to poll the new blocks those traces would not be available. This should be noted on the configuration option, but does not need to be solved.

### PR DESCRIPTION
**Pull request by mghildiy**
[Ingester] Add ability to completely flush on shutdown

**Which issue(s) this PR fixes**:
Fixes #699

**Checklist**
- [ ] Tests updated
- [x] Documentation added
- [x] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Review by joe-elliott — APPROVED** [review]
Looks great! Thanks for digging into this. Please add a changelog entry and we'll merge.

**Comment by mghildiy** [comment]
> Looks great! Thanks for digging into this. Please add a changelog entry and we'll merge.

I have already added it in CHANGELOG.md.

**Comment by joe-elliott** [comment]
> I have already added it in CHANGELOG.md.
Not sure how I missed that. Thanks!

**Comment by mghildiy** [comment]
TestInstanceSearchDoesNotRace failed.

I checked its code, and I see several concurrent functions. May be thats making it flaky.

**Comment by joe-elliott** [comment]
> TestInstanceSearchDoesNotRace failed.
> I checked its code, and I see several concurrent functions. May be thats making it flaky.

Yeah. It's meant to concurrency issues and it is. The issue is documented here: https://github.com/grafana/tempo/issues/2534

**Review by mapno — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
