### PR TITLE
[DOC] Sync back website changes

### PR DESCRIPTION
**Pull request by jdbaldry**
Since this release branch has no docs publishing workflow, changes have been made in the website repository.

This PR syncs back those changes.

### CODE REVIEW

**Comment by jdbaldry** [comment]
These aliases are the ones currently in use on the website so I think they are preferable to whatever we have in this repository currently.

**Review by knylander-grafana — APPROVED** [review]
Changes fix aliases to point to the correct version of the docs instead of the latest (2.2 instead of 1.2).

**Review by knylander-grafana — APPROVED** [review]

**Comment by knylander-grafana** [comment]
@jdbaldry I haven't merged this PR because all of the tests keep failing. I'm not sure if that indicates that the tests are for 2.x Tempo or what. do we need to worry about the checks for doc?

**Comment by jdbaldry** [comment]
I think the repository maintainers are best to decide whether the failing tests are problematic. My guess is that they are unrelated to my changes and are just a result of CI degradation on this branch.

**Pull request merged**
