### PR TITLE
Serve config at HTTP endpoint

### PR DESCRIPTION
**Pull request by annanay25**
Signed-off-by: Annanay <annanayagarwal@gmail.com>

**What this PR does**:
Adds a `/config` handler to serve the config that tempo is running with. Makes it easier to debug in non-k8s environments.

Long term, we should add an API module similar to Cortex. 

**Which issue(s) this PR fixes**:
Fixes #nada

**Checklist**
- NA Tests updated
- NA Documentation added
- [x] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Review by joe-elliott — COMMENTED** [review]
Tempo can include sensitive information in its config.  We either need to find a way to redact that or perhaps only serve this endpoint if it's configured.

**Comment by annanay25** [comment]
Good point, I had not considered that. I was following suit with Cortex, which serves config by default I guess.

**Comment by annanay25** [comment]
Okay, cortex is clever :) - https://github.com/cortexproject/cortex/blob/master/pkg/util/flagext/secret.go

I'll reuse this.

**Comment by annanay25** [comment]
Results in

```
storage:
    trace:
        backend: s3
        local:
            path: ""
        gcs:
            bucket_name: ""
            chunk_buffer_size: 10485760
            endpoint: ""
            insecure: false
        s3:
            bucket: tempo
            endpoint: minio:9000
            access_key: '********'
            secret_key: '********'
            insecure: true
            part_size: 0
            signature_v2: false

```

**Review by joe-elliott — APPROVED** [review]

**Pull request merged**
