### PR TITLE
 Update to latest dskit

### PR DESCRIPTION
**Pull request by andreasgerstmayr**
**What this PR does**:
Update to latest dskit

**Which issue(s) this PR fixes**:
https://github.com/grafana/dskit/pull/518
https://github.com/grafana/dskit/pull/537
Prerequisite for #3646

**Checklist**
- [X] Tests updated
- [ ] Documentation added
- [X] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Comment by joe-elliott** [comment]
Thanks for the PR andreas! Heads up tests are broken atm: https://github.com/grafana/tempo/pull/3916

**Comment by andreasgerstmayr** [comment]
> Thanks for the PR andreas! Heads up tests are broken atm: #3916

Ah, that explains stuff. Thanks for the info. I got confused why the latest commit on the main branch is green, but I just noticed now that the unit tests do not run on the main branch commits. I assumed it's maybe a mismatch of my local Go version.

In the meantime, I hacked together a small util which shuffles the query parameters around (no actual value change) and manually updated the test cases in `search_sharder_test.go` .

**Comment by joe-elliott** [comment]
> In the meantime, I hacked together a small util which shuffles the query parameters around (no actual value change) and manually updated the test cases in search_sharder_test.go .

Yeah, I considered this as well. As far as I can tell the order is deterministic (no map iteration or other normal things that break these kind of things). Are tests passing regularly?

**Comment by joe-elliott** [comment]
@andreasgerstmayr got my PR merged and i think i prefer it to yours b/c it will survive future changes to the way we build those urls. can you drop the changes to the search sharder test?

**Comment by andreasgerstmayr** [comment]
> @andreasgerstmayr got my PR merged and i think i prefer it to yours b/c it will survive future changes to the way we build those urls. can you drop the changes to the search sharder test?

Good point! I dropped the search sharder test changes from this PR.

**Pull request merged**
