### PR TITLE
Chore: Upgrade Cortex

### PR DESCRIPTION
**Pull request by aknuds1**
**What this PR does**:
Upgrade to latest Cortex.

[Changes](https://github.com/cortexproject/cortex/compare/v1.9.0..a4bf1035478641626fcbdd5fd12325c08a2bba76) from Cortex v1.9.0 until a4bf10354786.

**Which issue(s) this PR fixes**:

**Checklist**
- [x] Tests updated
- [ ] Documentation added
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Review by annanay25 — COMMENTED** [review]
Thanks for the update @aknuds1 

Could you link the changelog between the old and new commit please? We would have to comb through it and look for any changes that might affect us.

**Comment by aknuds1** [comment]
> Thanks for the update @aknuds1
> 
> Could you link the changelog between the old and new commit please? We would have to comb through it and look for any changes that might affect us.

@annanay25 OK, will do.

**Comment by aknuds1** [comment]
@annanay25 added change comparison link between the two Cortex commits. Hope it's what you need.

**Comment by kvrhdn** [comment]
The [CHANGELOG](https://github.com/cortexproject/cortex/blob/master/CHANGELOG.md) is probably easier to parse.

**Comment by aknuds1** [comment]
> The [CHANGELOG](https://github.com/cortexproject/cortex/blob/master/CHANGELOG.md) is probably easier to parse.

Thanks @kvrhdn

**Review by kvrhdn — APPROVED** [review]
I don't see a lot of changes impacting Tempo, looks good to me :+1:
Glad this upgrade went smoother than my upgrade a couple of weeks ago 😅

**Review by annanay25 — COMMENTED** [review]
Relevant changes:
- Change in memberlist default values, might need changes to our jsonnet: https://github.com/cortexproject/cortex/pull/4276
- Compression of memberlist messages, ON by default, and no action needed: https://github.com/cortexproject/cortex/pull/4346 

Also, do we need to backport this change - https://github.com/cortexproject/cortex/pull/4375

**Review by annanay25 — APPROVED** [review]
lgtm.

**Review by annanay25 — COMMENTED** [review]
Can you please add a CHANGELOG entry. This is looking good to go.

**Comment by aknuds1** [comment]
> Can you please add a CHANGELOG entry. This is looking good to go.

Thanks @annanay25, done.

**Pull request merged**
