### PR TITLE
2.6: Update parque-go with IBM Z support

### PR DESCRIPTION
**Pull request by pavolloffay**
**What this PR does**:

Backported https://github.com/grafana/tempo/pull/4175 

**Which issue(s) this PR fixes**:
Fixes #<issue number>

**Checklist**
- [ ] Tests updated
- [ ] Documentation added
- [x] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Review by joe-elliott — COMMENTED** [review]
changelog? also CI is going to yell at you b/c you didn't revendor parquet-go

**Comment by pavolloffay** [comment]
I am not sure why` CI / Run integration tests (test-e2e-serverless) (pull_request` failed

**Comment by joe-elliott** [comment]
Let's make this PR against main, then we will backport to release-2.6

**Comment by pavolloffay** [comment]
See https://github.com/grafana/tempo/pull/4175

**Pull request closed without merging**
