### PR TITLE
drone: remove serverless pipeline

### PR DESCRIPTION
**Pull request by javiermolinar**
**What this PR does**:
Remove the serverless pipeline. It also changes the release trigger from `tag` and `pull-request` to just tag. Now we are doing all the steps but the last final release one more than needed

### CODE REVIEW

**Comment by kvrhdn** [comment]
I think you might have an indentation issue? The diff is really confusing

Screenshot 2024-10-18 at 13 13 37

You can use `jsonnetfmt` to format your code

```
jsonnetfmt -i .drone/drone.jsonnet
```

**Comment by javiermolinar** [comment]
> jsonnetfmt -i .drone/drone.jsonnet

It was wrongly indented before

**Review by kvrhdn — COMMENTED** [review]
Left some comments for missed variables etc.

But mostly I'm wondering _if_ we want to remove this pipeline? Pushing the images is a pretty small cost (I assume) and setting this back up would be a lot of effort. So maybe we should decide first what we do with serverless support going forward.

**Comment by electron0zero** [comment]
> I'm wondering _if_ we want to remove this pipeline?

I would say let's put this PR on hold till we make a decision on the future of serverless in Tempo (mostly the answer is no, but we need to sit down and make a proper decision).

I agree with Yuna that it's little gain and if we need to invest back into serverless, it will be a lot of effort to set it back.

**Comment by javiermolinar** [comment]
> > I'm wondering _if_ we want to remove this pipeline?
> 
> I would say let's put this PR on hold till we make a decision on the future of serverless functions in Tempo (see #4014).
> 
> I agree with @kvrhdn that if we decide to keep serverless functions around, it will be a lot of effort to set it back up.

I can drop it if we think it's still valuable. Thank you both for the review

**Pull request closed without merging**
