### PR TITLE
Fixed multiple typos

### PR DESCRIPTION
**Pull request by xogoodnow**
Fixed multiple typos within the project

### CODE REVIEW

**Review by knylander-grafana — APPROVED** [review]
Thank you for fixing the duplicate words!

**Comment by xogoodnow** [comment]
Hi @knylander-grafana 

It ain't that important,  I'm just a little OCD :)
Thanks for your time 

Cheers

**Comment by joe-elliott** [comment]
> It ain't that important, I'm just a little OCD :)

no need to diminish submitting your PR. we really appreciate any effort to improve the codebase and docs. lgtm. will merge after tests pass.

**Review by joe-elliott — APPROVED** [review]

**Comment by xogoodnow** [comment]
Hi, @joe-elliott, 
very kind of you :beers:

**Comment by xogoodnow** [comment]
I mistakenly added another file and then removed it. I believe this action caused the pipeline to crash.

**Pull request merged**
