### PR TITLE
readd session token to s3 credentials

### PR DESCRIPTION
**Pull request by farodin91**
**What this PR does**:
Support was removed in https://github.com/grafana/tempo/pull/3006

**Which issue(s) this PR fixes**:
Fixes #<issue number>

**Checklist**
- [ ] Tests updated
- [ ] Documentation added
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Comment by joe-elliott** [comment]
Thanks for catching and fixing this. Can you add a changelog entry?

**Comment by farodin91** [comment]
changelog added

**Review by joe-elliott — APPROVED** [review]
Looks good! Thanks for the fix. Do you need this backported to use 2.3?

cc @mapno

**Comment by farodin91** [comment]
@joe-elliott Would be nice.

**Pull request merged**
