### PR TITLE
Chore: Use services and modules from grafana/dskit

### PR DESCRIPTION
**Pull request by 56quarters**
**What this PR does**:

Updates to the latest Cortex commit in order to make use of grafana/dskit modules and services instead of their (now removed) Cortex counterparts.

**Notes to reviewer**:

The vendor update is in a separate commit to hopefully make review a bit less noisy.

**Checklist**
- [X] Tests updated
- [ ] Documentation added
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Comment by joe-elliott** [comment]
Thanks! We will merge this after we cut 1.1.

**Review by annanay25 — COMMENTED** [review]
This is a dupe of #892, but ports more packages over. We are okay to merge either one now, I'll leave the decision to you folks :)

Thanks for the update! Please add a CHANGELOG entry for this.

**Review by joe-elliott — APPROVED** [review]

**Comment by 56quarters** [comment]
Rebased from latest main to resolve merge conflicts

**Comment by joe-elliott** [comment]
thanks!

**Pull request merged**
