### PR TITLE
Support for inline environments

### PR DESCRIPTION
**Pull request by irizzant**
**What this PR does**:
Adds support for inline environments (https://tanka.dev/inline-environments).

This way users can import the example they want to use (single binary, microservices) in their clusters.libsonnet file and customize any aspect of the environment they want to deploy.

**Which issue(s) this PR fixes**:

**Checklist**
- [X] Tests updated
- [X] Documentation added
- [X] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Comment by joe-elliott** [comment]
This is a fairly enormous update of dependencies in our jsonnet library that will be very difficult to review. Is it possible to make your addition without updating the dependencies?

Also a readme or other guide might be nice to help people understand why this pattern exists and what it is useful for.

**Comment by irizzant** [comment]
Hi @joe-elliott 
the amount of dependency updates you see are mostly because of the added dependency:
```
"remote": "https://github.com/grafana/jsonnet-libs.git",
"subdir": "tanka-util"
```
Also without updating the dependencies tanka would refuse rendering the manifests.

About the docs, let me know the way you'd prefer me to document this.

**Comment by irizzant** [comment]
Hi @joe-elliott 
let me see if I can detail better.

If I only add `tanka-util` library, I get the following error during manifestation:
```
tk show inline
Error: evaluating jsonnet: RUNTIME ERROR: function has no parameter allValue
        /home/local/INTRANET/ivan.rizzante/tempo/operations/tempo-mixin/dashboard-utils.libsonnet:(27:9)-(28:88)        function <anonymous>
        /home/local/INTRANET/ivan.rizzante/tempo/operations/tempo-mixin/dashboards.libsonnet:(9:7)-(10:37)
        /home/local/INTRANET/ivan.rizzante/tempo/example/tk/vendor/grafana/configmaps.libsonnet:69:31-54        thunk from <object <anonymous>>
        /home/local/INTRANET/ivan.rizzante/tempo/example/tk/vendor/grafana/configmaps.libsonnet:69:18-55        object <anonymous>
        /home/local/INTRANET/ivan.rizzante/tempo/example/tk/vendor/grafana/configmaps.libsonnet:72:32-41        thunk from <function <anonymous>>
        /home/local/INTRANET/ivan.rizzante/tempo/example/tk/vendor/grafana/configmaps.libsonnet:72:21-42        function <anonymous>
        /home/local/INTRANET/ivan.rizzante/tempo/example/tk/vendor/grafana/configmaps.libsonnet:(66:24)-(72:43) thunk <dashboards> from <function <anonymous>>
        /home/local/INTRANET/ivan.rizzante/tempo/example/tk/vendor/grafana/configmaps.libsonnet:73:30-40        thunk from <thunk <count> from <function <anonymous>>>
        /home/local/INTRANET/ivan.rizzante/tempo/example/tk/vendor/grafana/configmaps.libsonnet:73:19-41        thunk <count> from <function <anonymous>>
        /home/local/INTRANET/ivan.rizzante/tempo/example/tk/vendor/grafana/configmaps.libsonnet:77:32-37        thunk from <thunk <shardCount> from <function <anonymous>>>
        ...
        <std>:1293:5-33 function <anonymous>
        /home/local/INTRANET/ivan.rizzante/tempo/example/tk/vendor/grafana/configmaps.libsonnet:117:24-48       function <anonymous>
        /home/local/INTRANET/ivan.rizzante/tempo/example/tk/vendor/grafana/configmaps.libsonnet:(112:5)-(118:6)
        /home/local/INTRANET/ivan.rizzante/tempo/example/tk/vendor/grafana/configmaps.libsonnet:(112:5)-(118:6)
        /home/local/INTRANET/ivan.rizzante/tempo/example/tk/vendor/grafana/configmaps.libsonnet:122:13-63       function <anonymous>
        <std>:789:24-47 thunk from <function <aux>>
        <std>:789:9-57  function <aux>
        <std>:790:5-28  function <anonymous>
        /home/local/INTRANET/ivan.rizzante/tempo/example/tk/vendor/grafana/configmaps.libsonnet:(120:34)-(125:4)        object <anonymous>
        During manifestation
```

After updating the dependencies instead I get the manifests right.

**Comment by irizzant** [comment]
@joe-elliott I've added some docs in the readme you specified, please let me know

**Review by joe-elliott — APPROVED** [review]
Thanks @irizzant!

I'm not super familiar with the inline jsonnet pattern. Thanks for getting an example in our repo.

**Comment by irizzant** [comment]
You're most welcome @joe-elliott , thank you

**Pull request merged**
