### PR TITLE
Update parquet-go to latest commit in main

### PR DESCRIPTION
**Pull request by stoewer**
**What this PR does**:

Update the parquet-go dependency to the latest commit [962b3c5827c3](https://github.com/parquet-go/parquet-go/commit/962b3c5827c3c0de1f2be9fd8079823de00f076b)

**Which issue(s) this PR fixes**:
Fixes #<issue number>

**Checklist**
- [ ] Tests updated
- [ ] Documentation added
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Review by mdisibio — APPROVED** [review]

**Comment by mdisibio** [comment]
Have any benchmarks handy?  Curious to see the benefits of the new buffer pool.

**Comment by stoewer** [comment]
Benchmark results for `BackendBlockQueryRange`

This was the command I ran:
```bash
go test -mod=vendor -run='^#' -bench='BenchmarkBackendBlockQueryRange' -count=8 -benchtime=2s -timeout=30m -benchmem ./tempodb/encoding/vparquet3
```

Summary by `benchstat`
```
goos: linux
goarch: amd64
pkg: github.com/grafana/tempo/tempodb/encoding/vparquet3
cpu: AMD Ryzen 7 PRO 6850U with Radeon Graphics     
                                                                             │ bench-query-range-run-05-main.txt │ bench-query-range-run-05-update-parquet-go.txt │
                                                                             │              sec/op               │          sec/op           vs base              │
BackendBlockQueryRange/{}_|_rate()/2-16                                                              35.76m ± 3%                35.00m ± 3%       ~ (p=0.161 n=8)
BackendBlockQueryRange/{}_|_rate()/4-16                                                              36.64m ± 3%                36.60m ± 3%       ~ (p=0.574 n=8)
BackendBlockQueryRange/{}_|_rate()_by_(name)/2-16                                                    62.85m ± 3%                62.40m ± 2%       ~ (p=0.442 n=8)
BackendBlockQueryRange/{}_|_rate()_by_(name)/4-16                                                    72.24m ± 3%                72.55m ± 3%       ~ (p=0.442 n=8)
BackendBlockQueryRange/{}_|_rate()_by_(resource.service.name)/2-16                                   46.63m ± 1%                46.59m ± 1%       ~ (p=0.645 n=8)
BackendBlockQueryRange/{}_|_rate()_by_(resource.service.name)/4-16                                   55.59m ± 1%                55.15m ± 2%       ~ (p=0.328 n=8)
BackendBlockQueryRange/{}_|_rate()_by_(span.http.url)/2-16                                           76.88m ± 3%                77.50m ± 2%       ~ (p=1.000 n=8)
BackendBlockQueryRange/{}_|_rate()_by_(span.http.url)/4-16                                           87.48m ± 3%                85.08m ± 2%  -2.75% (p=0.007 n=8)
BackendBlockQueryRange/{resource.service.name=`loki-ingester`}_|_rate()/2-16                         27.32m ± 4%                26.88m ± 6%       ~ (p=0.442 n=8)
BackendBlockQueryRange/{resource.service.name=`loki-ingester`}_|_rate()/4-16                         27.82m ± 1%                27.45m ± 1%  -1.32% (p=0.000 n=8)
BackendBlockQueryRange/{status=error}_|_rate()/2-16                                                  21.53m ± 1%                21.76m ± 4%       ~ (p=0.721 n=8)
BackendBlockQueryRange/{status=error}_|_rate()/4-16                                                  21.47m ± 1%                21.17m ± 1%  -1.40% (p=0.001 n=8)
geomean                                                                                              42.67m                     42.36m       -0.72%

                                                                             │ bench-query-range-run-05-main.txt │ bench-query-range-run-05-update-parquet-go.txt │
                                                                             │             MB_IO/op              │        MB_IO/op         vs base                │
BackendBlockQueryRange/{}_|_rate()/2-16                                                               9.011 ± 0%               9.011 ± 0%       ~ (p=1.000 n=8) ¹
BackendBlockQueryRange/{}_|_rate()/4-16                                                               9.011 ± 0%               9.011 ± 0%       ~ (p=1.000 n=8) ¹
BackendBlockQueryRange/{}_|_rate()_by_(name)/2-16                                                     13.00 ± 0%               13.00 ± 0%       ~ (p=1.000 n=8) ¹
BackendBlockQueryRange/{}_|_rate()_by_(name)/4-16                                                     13.00 ± 0%               13.00 ± 0%       ~ (p=1.000 n=8) ¹
BackendBlockQueryRange/{}_|_rate()_by_(resource.service.name)/2-16                                    9.220 ± 0%               9.220 ± 0%       ~ (p=1.000 n=8) ¹
BackendBlockQueryRange/{}_|_rate()_by_(resource.service.name)/4-16                                    9.220 ± 0%               9.220 ± 0%       ~ (p=1.000 n=8) ¹
BackendBlockQueryRange/{}_|_rate()_by_(span.http.url)/2-16                                            10.60 ± 0%               10.60 ± 0%       ~ (p=1.000 n=8) ¹
BackendBlockQueryRange/{}_|_rate()_by_(span.http.url)/4-16                                            10.60 ± 0%               10.60 ± 0%       ~ (p=1.000 n=8) ¹
BackendBlockQueryRange/{resource.service.name=`loki-ingester`}_|_rate()/2-16                          9.220 ± 0%               9.220 ± 0%       ~ (p=1.000 n=8) ¹
BackendBlockQueryRange/{resource.service.name=`loki-ingester`}_|_rate()/4-16                          9.220 ± 0%               9.220 ± 0%       ~ (p=1.000 n=8) ¹
BackendBlockQueryRange/{status=error}_|_rate()/2-16                                                   9.910 ± 0%               9.910 ± 0%       ~ (p=1.000 n=8) ¹
BackendBlockQueryRange/{status=error}_|_rate()/4-16                                                   9.910 ± 0%               9.910 ± 0%       ~ (p=1.000 n=8) ¹
geomean                                                                                               10.08                    10.08       +0.00%
¹ all samples are equal

                                                                             │ bench-query-range-run-05-main.txt │ bench-query-range-run-05-update-parquet-go.txt │
                                                                             │             spans/op              │        spans/op         vs base                │
BackendBlockQueryRange/{}_|_rate()/2-16                                                              32.03k ± 0%              32.03k ± 0%       ~ (p=1.000 n=8) ¹
BackendBlockQueryRange/{}_|_rate()/4-16                                                              78.56k ± 0%              78.56k ± 0%       ~ (p=1.000 n=8) ¹
BackendBlockQueryRange/{}_|_rate()_by_(name)/2-16                                                    32.03k ± 0%              32.03k ± 0%       ~ (p=1.000 n=8) ¹
BackendBlockQueryRange/{}_|_rate()_by_(name)/4-16                                                    78.56k ± 0%              78.56k ± 0%       ~ (p=1.000 n=8) ¹
BackendBlockQueryRange/{}_|_rate()_by_(resource.service.name)/2-16                                   32.03k ± 0%              32.03k ± 0%       ~ (p=1.000 n=8) ¹
BackendBlockQueryRange/{}_|_rate()_by_(resource.service.name)/4-16                                   78.56k ± 0%              78.56k ± 0%       ~ (p=1.000 n=8) ¹
BackendBlockQueryRange/{}_|_rate()_by_(span.http.url)/2-16                                           32.03k ± 0%              32.03k ± 0%       ~ (p=1.000 n=8) ¹
BackendBlockQueryRange/{}_|_rate()_by_(span.http.url)/4-16                                           78.56k ± 0%              78.56k ± 0%       ~ (p=1.000 n=8) ¹
BackendBlockQueryRange/{resource.service.name=`loki-ingester`}_|_rate()/2-16                         5.926k ± 0%              5.926k ± 0%       ~ (p=1.000 n=8) ¹
BackendBlockQueryRange/{resource.service.name=`loki-ingester`}_|_rate()/4-16                         19.02k ± 0%              19.02k ± 0%       ~ (p=1.000 n=8) ¹
BackendBlockQueryRange/{status=error}_|_rate()/2-16                                                   999.0 ± 0%               999.0 ± 0%       ~ (p=1.000 n=8) ¹
BackendBlockQueryRange/{status=error}_|_rate()/4-16                                                  2.041k ± 0%              2.041k ± 0%       ~ (p=1.000 n=8) ¹
geomean                                                                                              21.40k                   21.40k       +0.00%
¹ all samples are equal

                                                                             │ bench-query-range-run-05-main.txt │ bench-query-range-run-05-update-parquet-go.txt │
                                                                             │              spans/s              │         spans/s           vs base              │
BackendBlockQueryRange/{}_|_rate()/2-16                                                              895.5k ± 1%               915.0k ±  3%       ~ (p=0.161 n=8)
BackendBlockQueryRange/{}_|_rate()/4-16                                                              2.144M ± 3%               2.146M ±  8%       ~ (p=0.574 n=8)
BackendBlockQueryRange/{}_|_rate()_by_(name)/2-16                                                    509.6k ± 2%               513.2k ±  4%       ~ (p=0.442 n=8)
BackendBlockQueryRange/{}_|_rate()_by_(name)/4-16                                                    1.088M ± 2%               1.083M ±  2%       ~ (p=0.442 n=8)
BackendBlockQueryRange/{}_|_rate()_by_(resource.service.name)/2-16                                   686.8k ± 1%               687.4k ±  2%       ~ (p=0.645 n=8)
BackendBlockQueryRange/{}_|_rate()_by_(resource.service.name)/4-16                                   1.413M ± 2%               1.424M ± 19%       ~ (p=0.328 n=8)
BackendBlockQueryRange/{}_|_rate()_by_(span.http.url)/2-16                                           416.6k ± 5%               413.2k ±  2%       ~ (p=1.000 n=8)
BackendBlockQueryRange/{}_|_rate()_by_(span.http.url)/4-16                                           898.0k ± 3%               923.4k ±  3%  +2.83% (p=0.007 n=8)
BackendBlockQueryRange/{resource.service.name=`loki-ingester`}_|_rate()/2-16                         216.9k ± 3%               220.4k ±  4%       ~ (p=0.442 n=8)
BackendBlockQueryRange/{resource.service.name=`loki-ingester`}_|_rate()/4-16                         683.8k ± 1%               693.0k ±  1%  +1.34% (p=0.000 n=8)
BackendBlockQueryRange/{status=error}_|_rate()/2-16                                                  46.40k ± 1%               45.91k ±  3%       ~ (p=0.721 n=8)
BackendBlockQueryRange/{status=error}_|_rate()/4-16                                                  95.05k ± 1%               96.41k ±  1%  +1.42% (p=0.001 n=8)
geomean                                                                                              501.5k                    505.1k        +0.73%

                                                                             │ bench-query-range-run-05-main.txt │ bench-query-range-run-05-update-parquet-go.txt │
                                                                             │               B/op                │           B/op            vs base              │
BackendBlockQueryRange/{}_|_rate()/2-16                                                            2.471Mi ± 20%              2.158Mi ± 18%       ~ (p=0.195 n=8)
BackendBlockQueryRange/{}_|_rate()/4-16                                                            2.534Mi ± 26%              2.431Mi ± 23%       ~ (p=0.645 n=8)
BackendBlockQueryRange/{}_|_rate()_by_(name)/2-16                                                  2.806Mi ± 19%              2.468Mi ± 14%       ~ (p=0.161 n=8)
BackendBlockQueryRange/{}_|_rate()_by_(name)/4-16                                                  2.728Mi ± 32%              3.192Mi ± 33%       ~ (p=0.195 n=8)
BackendBlockQueryRange/{}_|_rate()_by_(resource.service.name)/2-16                                 2.186Mi ± 14%              2.597Mi ± 30%       ~ (p=0.195 n=8)
BackendBlockQueryRange/{}_|_rate()_by_(resource.service.name)/4-16                                 2.552Mi ± 15%              2.319Mi ± 16%       ~ (p=0.328 n=8)
BackendBlockQueryRange/{}_|_rate()_by_(span.http.url)/2-16                                         11.79Mi ±  7%              12.61Mi ±  5%  +6.89% (p=0.028 n=8)
BackendBlockQueryRange/{}_|_rate()_by_(span.http.url)/4-16                                         12.62Mi ± 10%              12.21Mi ±  4%       ~ (p=0.505 n=8)
BackendBlockQueryRange/{resource.service.name=`loki-ingester`}_|_rate()/2-16                       2.287Mi ± 15%              2.299Mi ±  9%       ~ (p=0.721 n=8)
BackendBlockQueryRange/{resource.service.name=`loki-ingester`}_|_rate()/4-16                       2.078Mi ± 13%              2.108Mi ±  7%       ~ (p=0.645 n=8)
BackendBlockQueryRange/{status=error}_|_rate()/2-16                                                1.605Mi ±  6%              1.607Mi ±  3%       ~ (p=0.798 n=8)
BackendBlockQueryRange/{status=error}_|_rate()/4-16                                                1.670Mi ±  8%              1.613Mi ±  6%       ~ (p=0.234 n=8)
geomean                                                                                            2.988Mi                    2.975Mi        -0.43%

                                                                             │ bench-query-range-run-05-main.txt │ bench-query-range-run-05-update-parquet-go.txt │
                                                                             │             allocs/op             │        allocs/op          vs base              │
BackendBlockQueryRange/{}_|_rate()/2-16                                                              23.30k ± 0%                23.30k ± 0%       ~ (p=0.182 n=8)
BackendBlockQueryRange/{}_|_rate()/4-16                                                              23.31k ± 0%                23.31k ± 0%       ~ (p=0.775 n=8)
BackendBlockQueryRange/{}_|_rate()_by_(name)/2-16                                                    24.38k ± 0%                24.38k ± 0%       ~ (p=0.369 n=8)
BackendBlockQueryRange/{}_|_rate()_by_(name)/4-16                                                    24.44k ± 0%                24.45k ± 0%       ~ (p=0.138 n=8)
BackendBlockQueryRange/{}_|_rate()_by_(resource.service.name)/2-16                                   23.63k ± 0%                23.64k ± 0%       ~ (p=0.217 n=8)
BackendBlockQueryRange/{}_|_rate()_by_(resource.service.name)/4-16                                   23.64k ± 0%                23.64k ± 0%       ~ (p=0.336 n=8)
BackendBlockQueryRange/{}_|_rate()_by_(span.http.url)/2-16                                           38.87k ± 1%                38.80k ± 1%       ~ (p=0.574 n=8)
BackendBlockQueryRange/{}_|_rate()_by_(span.http.url)/4-16                                           39.01k ± 0%                39.82k ± 2%  +2.07% (p=0.001 n=8)
BackendBlockQueryRange/{resource.service.name=`loki-ingester`}_|_rate()/2-16                         22.06k ± 0%                22.06k ± 0%       ~ (p=0.766 n=8)
BackendBlockQueryRange/{resource.service.name=`loki-ingester`}_|_rate()/4-16                         22.06k ± 0%                22.06k ± 0%       ~ (p=0.483 n=8)
BackendBlockQueryRange/{status=error}_|_rate()/2-16                                                  22.20k ± 0%                22.20k ± 0%       ~ (p=0.972 n=8)
BackendBlockQueryRange/{status=error}_|_rate()/4-16                                                  22.20k ± 0%                22.20k ± 0%       ~ (p=0.166 n=8)
geomean                                                                                              25.20k                     25.24k       +0.16%

```

**Comment by stoewer** [comment]
Benchmark results for `BackendBlockTraceQL`

This was the command I ran:
```bash
go test -mod=vendor -run='^#' -bench='BackendBlockTraceQL' -count=8 -benchtime=2s -timeout=30m -benchmem ./tempodb/encoding/vparquet3
```

Summary by `benchstat`
```
goos: linux
goarch: amd64
pkg: github.com/grafana/tempo/tempodb/encoding/vparquet3
cpu: AMD Ryzen 7 PRO 6850U with Radeon Graphics     
                                                    │ bench-traceql-run-03-main.txt │ bench-traceql-run-03-update-parquet-go.txt │
                                                    │            sec/op             │        sec/op         vs base              │
BackendBlockTraceQL/spanAttValMatch-16                                  1.007 ±  2%            1.027 ±  1%  +1.93% (p=0.000 n=8)
BackendBlockTraceQL/spanAttValNoMatch-16                               31.56m ±  3%           31.79m ±  1%       ~ (p=0.442 n=8)
BackendBlockTraceQL/spanAttIntrinsicMatch-16                           424.3m ±  1%           432.2m ±  2%  +1.87% (p=0.003 n=8)
BackendBlockTraceQL/spanAttIntrinsicNoMatch-16                         4.142m ±  2%           4.135m ±  2%       ~ (p=0.959 n=8)
BackendBlockTraceQL/resourceAttValMatch-16                              4.552 ±  1%            4.652 ±  1%  +2.19% (p=0.000 n=8)
BackendBlockTraceQL/resourceAttValNoMatch-16                           2.384m ±  1%           2.450m ±  1%  +2.77% (p=0.000 n=8)
BackendBlockTraceQL/resourceAttIntrinsicMatch-16                       178.2m ±  1%           180.9m ±  2%  +1.47% (p=0.015 n=8)
BackendBlockTraceQL/resourceAttIntrinsicMatch#01-16                    2.503m ±  1%           2.538m ±  1%  +1.38% (p=0.000 n=8)
BackendBlockTraceQL/mixedValNoMatch-16                                  2.410 ±  4%            2.424 ±  3%       ~ (p=0.505 n=8)
BackendBlockTraceQL/mixedValMixedMatchAnd-16                           2.619m ±  1%           2.668m ±  1%  +1.87% (p=0.010 n=8)
BackendBlockTraceQL/mixedValMixedMatchOr-16                             1.851 ±  2%            1.868 ±  3%       ~ (p=0.279 n=8)
BackendBlockTraceQL/count-16                                            4.053 ±  1%            4.173 ±  1%  +2.95% (p=0.000 n=8)
BackendBlockTraceQL/struct-16                                           7.364 ± 13%            7.505 ± 16%       ~ (p=0.574 n=8)
BackendBlockTraceQL/||-16                                               1.317 ±  1%            1.351 ±  1%  +2.55% (p=0.000 n=8)
BackendBlockTraceQL/mixed-16                                           534.4m ±  1%           555.6m ±  1%  +3.97% (p=0.000 n=8)
geomean                                                                209.6m                 213.4m        +1.79%

                                                    │ bench-traceql-run-03-main.txt │ bench-traceql-run-03-update-parquet-go.txt │
                                                    │              B/s              │         B/s           vs base              │
BackendBlockTraceQL/spanAttValMatch-16                                178.0Mi ±  1%          174.7Mi ±  2%  -1.89% (p=0.000 n=8)
BackendBlockTraceQL/spanAttValNoMatch-16                              454.3Mi ±  3%          451.0Mi ±  2%       ~ (p=0.442 n=8)
BackendBlockTraceQL/spanAttIntrinsicMatch-16                          436.7Mi ±  1%          428.7Mi ±  1%  -1.84% (p=0.003 n=8)
BackendBlockTraceQL/spanAttIntrinsicNoMatch-16                        2.908Gi ±  2%          2.914Gi ±  2%       ~ (p=0.959 n=8)
BackendBlockTraceQL/resourceAttValMatch-16                            38.91Mi ±  1%          38.07Mi ±  1%  -2.16% (p=0.000 n=8)
BackendBlockTraceQL/resourceAttValNoMatch-16                          210.6Mi ±  1%          204.9Mi ±  1%  -2.70% (p=0.000 n=8)
BackendBlockTraceQL/resourceAttIntrinsicMatch-16                      744.9Mi ±  1%          734.1Mi ±  1%  -1.45% (p=0.015 n=8)
BackendBlockTraceQL/resourceAttIntrinsicMatch#01-16                   352.1Mi ±  1%          347.3Mi ±  1%  -1.36% (p=0.000 n=8)
BackendBlockTraceQL/mixedValNoMatch-16                                12.26Mi ±  3%          12.20Mi ±  4%       ~ (p=0.488 n=8)
BackendBlockTraceQL/mixedValMixedMatchAnd-16                          666.5Mi ±  5%          654.3Mi ±  1%  -1.84% (p=0.010 n=8)
BackendBlockTraceQL/mixedValMixedMatchOr-16                           43.08Mi ±  2%          42.69Mi ±  5%       ~ (p=0.279 n=8)
BackendBlockTraceQL/count-16                                          43.01Mi ±  2%          41.78Mi ±  0%  -2.86% (p=0.000 n=8)
BackendBlockTraceQL/struct-16                                         25.28Mi ± 10%          24.81Mi ± 10%       ~ (p=0.574 n=8)
BackendBlockTraceQL/||-16                                             135.1Mi ±  1%          131.8Mi ±  1%  -2.49% (p=0.000 n=8)
BackendBlockTraceQL/mixed-16                                          328.4Mi ±  2%          315.9Mi ±  1%  -3.82% (p=0.000 n=8)
geomean                                                               173.4Mi                170.3Mi        -1.76%

                                                    │ bench-traceql-run-03-main.txt │ bench-traceql-run-03-update-parquet-go.txt │
                                                    │           MB_io/op            │      MB_io/op       vs base                │
BackendBlockTraceQL/spanAttValMatch-16                                   188.0 ± 0%           188.0 ± 0%       ~ (p=1.000 n=8) ¹
BackendBlockTraceQL/spanAttValNoMatch-16                                 15.03 ± 0%           15.03 ± 0%       ~ (p=1.000 n=8) ¹
BackendBlockTraceQL/spanAttIntrinsicMatch-16                             194.3 ± 0%           194.3 ± 0%       ~ (p=1.000 n=8) ¹
BackendBlockTraceQL/spanAttIntrinsicNoMatch-16                           12.94 ± 0%           12.94 ± 0%       ~ (p=1.000 n=8) ¹
BackendBlockTraceQL/resourceAttValMatch-16                               185.7 ± 0%           185.7 ± 0%       ~ (p=1.000 n=8) ¹
BackendBlockTraceQL/resourceAttValNoMatch-16                            526.4m ± 0%          526.4m ± 0%       ~ (p=1.000 n=8) ¹
BackendBlockTraceQL/resourceAttIntrinsicMatch-16                         139.2 ± 0%           139.2 ± 0%       ~ (p=1.000 n=8) ¹
BackendBlockTraceQL/resourceAttIntrinsicMatch#01-16                     924.2m ± 0%          924.2m ± 0%       ~ (p=1.000 n=8) ¹
BackendBlockTraceQL/mixedValNoMatch-16                                   30.99 ± 0%           30.99 ± 0%       ~ (p=1.000 n=8) ¹
BackendBlockTraceQL/mixedValMixedMatchAnd-16                             1.830 ± 0%           1.830 ± 0%       ~ (p=1.000 n=8) ¹
BackendBlockTraceQL/mixedValMixedMatchOr-16                              83.62 ± 0%           83.62 ± 0%       ~ (p=1.000 n=8) ¹
BackendBlockTraceQL/count-16                                             182.8 ± 0%           182.8 ± 0%       ~ (p=1.000 n=8) ¹
BackendBlockTraceQL/struct-16                                            195.2 ± 0%           195.2 ± 0%       ~ (p=1.000 n=8) ¹
BackendBlockTraceQL/||-16                                                186.7 ± 0%           186.7 ± 0%       ~ (p=1.000 n=8) ¹
BackendBlockTraceQL/mixed-16                                             184.0 ± 0%           184.0 ± 0%       ~ (p=1.000 n=8) ¹
geomean                                                                  38.11                38.11       +0.00%
¹ all samples are equal

                                                    │ bench-traceql-run-03-main.txt │ bench-traceql-run-03-update-parquet-go.txt │
                                                    │             B/op              │         B/op          vs base              │
BackendBlockTraceQL/spanAttValMatch-16                                200.2Mi ±  4%          200.3Mi ±  2%       ~ (p=0.959 n=8)
BackendBlockTraceQL/spanAttValNoMatch-16                              35.64Mi ±  2%          36.29Mi ±  2%  +1.81% (p=0.005 n=8)
BackendBlockTraceQL/spanAttIntrinsicMatch-16                          47.97Mi ±  6%          47.74Mi ±  7%       ~ (p=0.878 n=8)
BackendBlockTraceQL/spanAttIntrinsicNoMatch-16                        1.829Mi ±  2%          1.813Mi ±  1%  -0.88% (p=0.010 n=8)
BackendBlockTraceQL/resourceAttValMatch-16                            3.637Gi ±  1%          3.640Gi ±  0%       ~ (p=0.234 n=8)
BackendBlockTraceQL/resourceAttValNoMatch-16                          1.389Mi ±  1%          1.385Mi ±  1%       ~ (p=0.442 n=8)
BackendBlockTraceQL/resourceAttIntrinsicMatch-16                      18.40Mi ±  8%          18.16Mi ±  6%       ~ (p=0.645 n=8)
BackendBlockTraceQL/resourceAttIntrinsicMatch#01-16                   1.426Mi ±  1%          1.428Mi ±  1%       ~ (p=0.721 n=8)
BackendBlockTraceQL/mixedValNoMatch-16                                50.00Mi ±  9%          50.29Mi ± 24%       ~ (p=0.489 n=8)
BackendBlockTraceQL/mixedValMixedMatchAnd-16                          1.412Mi ±  1%          1.413Mi ±  1%       ~ (p=0.505 n=8)
BackendBlockTraceQL/mixedValMixedMatchOr-16                           7.542Mi ± 52%          7.542Mi ± 52%       ~ (p=1.000 n=8)
BackendBlockTraceQL/count-16                                          3.102Gi ±  1%          3.102Gi ±  1%       ~ (p=0.878 n=8)
BackendBlockTraceQL/struct-16                                         198.4Mi ±  3%          203.9Mi ±  5%       ~ (p=0.065 n=8)
BackendBlockTraceQL/||-16                                             720.8Mi ±  3%          718.5Mi ±  2%       ~ (p=0.721 n=8)
BackendBlockTraceQL/mixed-16                                          32.09Mi ± 13%          32.50Mi ± 18%       ~ (p=0.721 n=8)
geomean                                                               38.72Mi                38.81Mi        +0.23%

                                                    │ bench-traceql-run-03-main.txt │ bench-traceql-run-03-update-parquet-go.txt │
                                                    │           allocs/op           │      allocs/op        vs base              │
BackendBlockTraceQL/spanAttValMatch-16                                  1.722M ± 0%            1.722M ± 0%       ~ (p=0.878 n=8)
BackendBlockTraceQL/spanAttValNoMatch-16                                20.42k ± 0%            20.42k ± 0%  +0.01% (p=0.011 n=8)
BackendBlockTraceQL/spanAttIntrinsicMatch-16                            295.0k ± 0%            295.0k ± 0%       ~ (p=0.981 n=8)
BackendBlockTraceQL/spanAttIntrinsicNoMatch-16                          20.23k ± 0%            20.23k ± 0%       ~ (p=0.267 n=8)
BackendBlockTraceQL/resourceAttValMatch-16                              23.91M ± 0%            23.91M ± 0%       ~ (p=0.130 n=8)
BackendBlockTraceQL/resourceAttValNoMatch-16                            20.26k ± 0%            20.26k ± 0%       ~ (p=1.000 n=8)
BackendBlockTraceQL/resourceAttIntrinsicMatch-16                        159.7k ± 0%            159.7k ± 0%       ~ (p=0.590 n=8)
BackendBlockTraceQL/resourceAttIntrinsicMatch#01-16                     20.26k ± 0%            20.26k ± 0%       ~ (p=1.000 n=8)
BackendBlockTraceQL/mixedValNoMatch-16                                  29.00k ± 0%            29.00k ± 0%       ~ (p=0.892 n=8)
BackendBlockTraceQL/mixedValMixedMatchAnd-16                            20.30k ± 0%            20.30k ± 0%       ~ (p=1.000 n=8)
BackendBlockTraceQL/mixedValMixedMatchOr-16                             38.93k ± 0%            38.93k ± 0%       ~ (p=0.970 n=8)
BackendBlockTraceQL/count-16                                            18.96M ± 0%            18.96M ± 0%       ~ (p=0.382 n=8)
BackendBlockTraceQL/struct-16                                           554.6k ± 5%            555.4k ± 4%       ~ (p=0.900 n=8)
BackendBlockTraceQL/||-16                                               4.001M ± 0%            4.001M ± 0%       ~ (p=0.594 n=8)
BackendBlockTraceQL/mixed-16                                            303.3k ± 0%            303.3k ± 0%       ~ (p=0.981 n=8)
geomean 
```

**Comment by stoewer** [comment]
Unfortunately the results are not very conclusive there is a slight decrease in performance for the TraceQL benchmark and a small improvement for the query range one

**Comment by mdisibio** [comment]
> Unfortunately the results are not very conclusive there is a slight decrease in performance for the TraceQL benchmark and a small improvement for the query range one

That's ok, thanks for running them.

**Pull request merged**
