### PR TITLE
Updated this page to refer to 'monolithic' instead of 'single binary'

### PR DESCRIPTION
**Pull request by 09jvilla**
We've standardized on this as the terminology we want to use for all of our backends, and have already made the changes in [Loki](https://grafana.com/docs/loki/next/fundamentals/architecture/deployment-modes/) and Mimir. See related slack [thread](https://raintank-corp.slack.com/archives/C02RJ13QB4K/p1645818793120839).

The rationale for moving away from 'single binary' is that Tempo (and Loki, and Mimir) are always a 'single binary', whether or not you are deploying as microservices.(In a microservices deployment, each component is the same 'single binary', but it just has a different value of the target flag.)

### CODE REVIEW

**Review by joe-elliott — COMMENTED** [review]
The term "single binary" occurs in a number of other places in the docs. should we go ahead and clean those up as well?

**Comment by 09jvilla** [comment]
Good point @joe-elliott . I took another crack at it. The helm charts, the target=scalable-single-binary, and a few URLs in the docs will still mention 'single binary', but I cleaned up the docs as much as possible and made a note that there may still be some legacy references.

**Comment by joe-elliott** [comment]
@09jvilla I was considering updating all of our examples (helm,tk,docker-compose) to use the new language but I was concerned that if I started changing the paths I would break some links. Instead I've added some notes here:

https://github.com/grafana/tempo/pull/1342/commits/dd33a6a42c6f9160e2ed78c1f6710d30726af1d2

Does this work? Should we update all of the examples terminology but leave the paths?

**Comment by 09jvilla** [comment]
> Does this work? 

Yea that would be my suggestion rather than the **Note** approach you took. I'm scared to change the name of the stuff pointed to by specific commands, like `single-binary-grafana-values.yaml` and the `tk apply tempo-single-binary` -- not sure if this will break folks, but updating the content of the readme itself seems fine.

**Comment by 09jvilla** [comment]
Feel free to just merge your commits on top of my PR.

**Review by joe-elliott — APPROVED** [review]

**Pull request merged**
