### PR TITLE
tempo-mixin: add Makefile and CI check

### PR DESCRIPTION
**Pull request by kvrhdn**
**What this PR does**:
- Adds a Makefile to simplify generating the tempo-mixin yamls.
- Link this Makefile to the root-level Makefile so you can do `make tempo-mixin`.
- Verify tempo-mixin has been updated in CI.

Should avoid issues like #956

**Which issue(s) this PR fixes**:
~~Fixes #<issue number>~~

**Checklist**
- [ ] ~~Tests updated~~
- [ ] ~~Documentation added~~
- [ ] ~~`CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`~~

### CODE REVIEW

**Comment by kvrhdn** [comment]
☝🏻  CI fails on _Check tempo-mixin_ because #956 hasn't been merged yet.

https://github.com/grafana/tempo/runs/3599938769

**Comment by kvrhdn** [comment]
Hmm, it's still failing 😞

**Comment by kvrhdn** [comment]
Okay, the diff is caused by trailing newline added by the C++ Jsonnet but not by go-jsonnet: https://github.com/google/go-jsonnet/issues/518

**Comment by kvrhdn** [comment]
Works now 😌

**Review by joe-elliott — APPROVED** [review]
nice!

**Pull request merged**
