### PR TITLE
Remove tempo-query from microservices deployment, Grafana connects to Tempo directly

### LINKED ISSUE #382: Remove dependency on Jaeger-Query
**Is your feature request related to a problem? Please describe.**
Currently Tempo requires Jaeger-Query as a translation layer between Tempo and Grafana.  This was a nice way to bootstrap the system, but we should drop the requirement to run this.  It is currently a performance issue that is seen particularly with large traces (#237).

**Describe the solution you'd like**
Add an endpoint to the querier that returns a trace in the Jaeger format for Grafana to consume.

### PR DESCRIPTION
**Pull request by annanay25**
**What this PR does**:
- Change API endpoint for querying traces. 
  - Query frontend `/api/traces/{traceID}` => `/tempo/api/traces/{traceID}`
  - Querier `/querier/api/traces/{traceID}` => `/querier/tempo/api/traces/{traceID}`
- Remove tempo-query from microservices jsonnet

**Which issue(s) this PR fixes**:
Fixes #382 

**Checklist**
- [ ] Tests updated
- [x] Documentation added
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Comment by joe-elliott** [comment]
Before merging this we need to determine what the migration path for production looks like.

**Comment by zswanson** [comment]
Are you able to update the architecture diagram to remove tempo-query too?
https://github.com/grafana/tempo/blob/master/docs/tempo/website/architecture/tempo_arch.png

**Comment by annanay25** [comment]
@zswanson - thanks for pointing out, will change that in a follow up PR.

**Review by joe-elliott — APPROVED** [review]
We need this as an emergency fix to our ops environment.  So......looks good enough for that :)

**Pull request merged**
