### PR TITLE
 update the opentelemetry module version from 0.97.0 to 0.102.1

### PR DESCRIPTION
**Pull request by debasishbsws**
**What this PR does**:

This PR basically try to update the opentelemetry module version from 0.97.0 to 0.102.1

The reason for this update is a high severity CVE https://github.com/advisories/GHSA-c74f-6mfw-mm4v that effect this software.

**Which issue(s) this PR fixes**:
Fixes #<issue number>

**Checklist**
- [x] Tests updated
- [ ] Documentation added
There is no functionality change
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

Even it dose not get merge, I want someone to update the module version to its latest. You can take this PR as a reference

### CODE REVIEW

**Comment by kvrhdn** [comment]
Thank you! I appreciate the quick PR, I was trying to make a similar update but got stuck on shim.go. I've approved the CI build.

Can you also update CHANGELOG.md?

**Comment by debasishbsws** [comment]
Hey @kvrhdn I have Updated the CHANGELOG.md.

**Comment by kvrhdn** [comment]
Thanks! Looks like CI is about two things:

- unused parameter
```
modules/distributor/receiver/shim.go:195:57: unused-parameter: parameter 'settings' seems to be unused, consider removing or renaming it as _ (revive)
	mockProviderFactory := confmap.NewProviderFactory(func(settings confmap.ProviderSettings) confmap.Provider {
```
- need to run `go mod tidy` in tempo-serverless

**Comment by debasishbsws** [comment]
Looks like all the test are passing 😃

**Review by kvrhdn — APPROVED** [review]
Verified with a quick test that the receiver config is being picked up :+1:

Can you address the merge conflict then we are ready to merge I think 🙂

**Comment by kvrhdn** [comment]
Once again, thank you for the quick PR!

**Pull request merged**
