### PR TITLE
Remove s3 bucket creation

### LINKED ISSUE #401: Remove Creation of s3 Bucket from s3 Backend
**Is your feature request related to a problem? Please describe.**
The s3 backend currently attempts to create a bucket if none exists.  Remove this and instead just fail on startup if no bucket exists.

Per @mdisibio in #397 
> Generally I am in favor of removing all bucket creation logic from tempo, since I think most users will have strong preferences/requirements on the creation of buckets (security/auditing/configuration/etc). This standpoint applies to S3 as well.

Additionally, creating the s3 bucket would require additional permissions which are not really necessary (except for one time bucket creation).

**Describe the solution you'd like**
Remove code that creates an s3 bucket if non exists.

### PR DESCRIPTION
**Pull request by dgzlopes**
**What this PR does**:
Removes the code that creates the S3 bucket.

**Which issue(s) this PR fixes**:
Fixes #401

**Checklist**
- [ ] Tests updated
- [X] Documentation added
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Comment by mdisibio** [comment]
This is great thank you.    

A couple thoughts:
* Do you know if the min.io example needs to be updated to create the bucket initially, or is ok?
* I think we can remove the s3 config Region value entirely now.  Min.IO can infer the region from the endpoint url.

**Comment by dgzlopes** [comment]
Thank you for taking the time to review :) 

- I'm not fully sure, I'll research it tomorrow.
- Nice! Removed.

**Comment by dgzlopes** [comment]
In theory, the Minio example should work b/c here:
```
mkdir -p /data/tempo && /usr/bin/minio server /data
```
When we create the new folder, we're creating a new bucket too.

**Review by annanay25 — APPROVED** [review]
LGTM. Thanks @dgzlopes!

**Comment by faceair** [comment]
Hi guys, the `region` field is useful.

There are many s3-compatible object stores that rely on this field when calculating signatures, and their endpoint is completely different from s3. For example, Baidu's object store https://cloud.baidu.com/doc/BOS/s/xjwvyq9l4

**Pull request merged**
