### PR TITLE
Bump github.com/prometheus/prometheus to v2.34.0

### LINKED ISSUE #1720: Metrics generator stopped generating span metrics for a tenant
**Describe the bug**

We have 4 tenants in a tempo cluster, after a point of time (at about 2022-09-05 17:17:00), one of those tenants has no span metrics generated any more, other tenants have no such issue.

After we restarted metrics-generator, it started to generate metrics for this tenant again

**To Reproduce**
Sorry that I don't find a way to reproduce this issue

**Environment:**
 - Infrastructure: Kubernetes

**Additional Context**

1. Some related metrics:

`rate(tempo_metrics_generator_spans_received_total{component="metrics-generator", tenant="infra"}[$__rate_interval])`:
image

`tempo_metrics_generator_registry_collections_total{component="metrics-generator", tenant="infra"}`:
image

`rate(prometheus_remote_storage_sent_batch_duration_seconds_count{component="metrics-generator", tenant="infra"}[$__rate_interval])`:
image

2. *No error/warning logs from metrics-generator at that time*

3. Tenant's config:
```yaml
infra:
    ingestion_rate_limit_bytes: 31457280
    ingestion_burst_size_bytes: 41943040
    max_traces_per_user: 50000
    metrics_generator_processors:
      - span-metrics
    block_retention: 168h
```

### PR DESCRIPTION
**Pull request by suraciii**
**What this PR does**:

This PR updated prometheus/prometheus dependency to v2.34.0, to apply a fix for deadlock in remote writing (https://github.com/prometheus/prometheus/pull/10395)

**Which issue(s) this PR fixes**:
Fixes #1720

**Checklist**
- [ ] Tests updated
- [ ] Documentation added
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Comment by kvrhdn** [comment]
It seems another PR has updated `go.sum` in the meantime, can you rebase this PR and resolve the merge conflicts? Besides that, it's good to merge I think 🙂

**Comment by suraciii** [comment]
> It seems another PR has updated `go.sum` in the meantime, can you rebase this PR and resolve the merge conflicts? Besides that, it's good to merge I think 🙂

Done :)

**Comment by suraciii** [comment]
@kvrhdn I pushed the fix for failed jobs, can you help to trigger them again?

**Review by kvrhdn — APPROVED** [review]
Nice! Thank you 🙌🏻

**Pull request merged**
